### PR TITLE
ml

### PR DESCRIPTION
**Pull request by Aliceliangwk**
update ml description

### CODE REVIEW

**Review by zhiyiyi — CHANGES_REQUESTED** [review]
Can you please clean `machine_learning.ipynb`'s output before push? And what machine learning algorithm you used for the analysis, can we name the file more specific instead of the very general name "machine_learning"?

**Comment by Aliceliangwk** [comment]
I created two ml notebook. one is called ARIMA deployment, which is the one I am going to use.  Another one ml notebook include two ml models I initially developed. Based on the feedback, I just updated the notebook name. Could you please review it. thanks!

**Review by zhiyiyi — CHANGES_REQUESTED** [review]
1. Please clean all the output of running notebook on local before commit
2. Only use lowercase letter and "_" for file names, for example, `my_file.ipynb`

**Comment by zhiyiyi** [comment]
Do you mind I change them for you @Aliceliangwk?

**Comment by Aliceliangwk** [comment]
I believed I already cleaned the output. In case I missed anything,  i dont mind you make changes at all. feel free to modify it. thanks!

**Review by zhiyiyi — APPROVED** [review]

**Pull request merged**
